# This file contains defaults for the "config" object used in the Snakefile.
# To temporarily override or provide a value, you can use snakemake's --config
# or --configfile options.
---
fasta_path: "/genfs/projects/COVID_consensus/release_data_freeze1/"
qc_meta: "~/meta/sgil_extract.tsv"
world_meta: "config/metadata_gsaid.tsv"
exclude_latest: "https://raw.githubusercontent.com/nextstrain/ncov/master/config/exclude.txt"
local_exclude: 'config/local_exclude.txt'
extra_fasta: "--extra_fasta_files config/Wuhan_WH01_2019.fasta ../data/aligned_21935_corrected_id_for_2020-09-02_13-11.fasta"

tree_method: "iqtree"
substitution-model: "GTR" # {HKY,GTR,HKY+G,GTR+G,GTR+R10}

canada_group: "200000"
neighbour_group: "2000000"

# filters
group_by: "region year month"
sequences_per_group: "1200000"  # 10 region year month get about 225 samples
sub_group_by: "region year month"
sub_sequences_per_group: "2"
min_length: 25000
exclude_where: "date='2015' "
max_date: "20200401" # YYYYMMDD
priority: "data/aligned_21935_score.txt"

# put the right input output connections in snakefile
ordering: "results/ordering.tsv"

include: "config/include.txt" # all QC data and two original wuhan are included
#include: "config/include_mini.txt" # all QC data and two original wuhan are included
reference: "config/coronavirus_Wuhan-Hu-1.gb" # the one used for assembly and alignment
outgroup: "config/outgroup.fasta"
color_schemes: "config/color_schemes.tsv"
auspice_config: "config/auspice_config.json"
auspice_config_gisaid: "config/auspice_config_gisaid.json"
auspice_config_zh: "config/auspice_config_zh.json"
lat_longs: "config/lat_longs.tsv"
description: "config/description_freeze1.md"
description_zh: "config/description_zh.md"
clades: "config/clades.tsv"

